# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:42:49+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Empty(BaseModel):
    pass


class DataProtectionMode(Enum):
    DATA_PROTECTION_MODE_UNSPECIFIED = 'DATA_PROTECTION_MODE_UNSPECIFIED'
    LIMITED_DATA_LOSS = 'LIMITED_DATA_LOSS'
    FORCE_DATA_LOSS = 'FORCE_DATA_LOSS'


class FailoverInstanceRequest(BaseModel):
    dataProtectionMode: Optional[DataProtectionMode] = Field(
        None,
        description="Optional. Available data protection modes that the user can choose. If it's unspecified, data protection mode will be LIMITED_DATA_LOSS by default.",
    )


class GcsDestination(BaseModel):
    uri: Optional[str] = Field(
        None,
        description="Required. Data destination URI (e.g. 'gs://my_bucket/my_object'). Existing files will be overwritten.",
    )


class GcsSource(BaseModel):
    uri: Optional[str] = Field(
        None,
        description="Required. Source data URI. (e.g. 'gs://my_bucket/my_object').",
    )


class GoogleCloudRedisV1OperationMetadata(BaseModel):
    apiVersion: Optional[str] = Field(None, description='API version.')
    cancelRequested: Optional[bool] = Field(
        None, description='Specifies if cancellation was requested for the operation.'
    )
    createTime: Optional[str] = Field(None, description='Creation timestamp.')
    endTime: Optional[str] = Field(None, description='End timestamp.')
    statusDetail: Optional[str] = Field(None, description='Operation status details.')
    target: Optional[str] = Field(None, description='Operation target.')
    verb: Optional[str] = Field(None, description='Operation verb.')


class GoogleCloudRedisV1ZoneMetadata(BaseModel):
    pass


class InputConfig(BaseModel):
    gcsSource: Optional[GcsSource] = Field(
        None,
        description='Google Cloud Storage location where input content is located.',
    )


class ConnectMode(Enum):
    CONNECT_MODE_UNSPECIFIED = 'CONNECT_MODE_UNSPECIFIED'
    DIRECT_PEERING = 'DIRECT_PEERING'
    PRIVATE_SERVICE_ACCESS = 'PRIVATE_SERVICE_ACCESS'


class ReadReplicasMode(Enum):
    READ_REPLICAS_MODE_UNSPECIFIED = 'READ_REPLICAS_MODE_UNSPECIFIED'
    READ_REPLICAS_DISABLED = 'READ_REPLICAS_DISABLED'
    READ_REPLICAS_ENABLED = 'READ_REPLICAS_ENABLED'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    CREATING = 'CREATING'
    READY = 'READY'
    UPDATING = 'UPDATING'
    DELETING = 'DELETING'
    REPAIRING = 'REPAIRING'
    MAINTENANCE = 'MAINTENANCE'
    IMPORTING = 'IMPORTING'
    FAILING_OVER = 'FAILING_OVER'


class SuspensionReason(Enum):
    SUSPENSION_REASON_UNSPECIFIED = 'SUSPENSION_REASON_UNSPECIFIED'
    CUSTOMER_MANAGED_KEY_ISSUE = 'CUSTOMER_MANAGED_KEY_ISSUE'


class Tier(Enum):
    TIER_UNSPECIFIED = 'TIER_UNSPECIFIED'
    BASIC = 'BASIC'
    STANDARD_HA = 'STANDARD_HA'


class TransitEncryptionMode(Enum):
    TRANSIT_ENCRYPTION_MODE_UNSPECIFIED = 'TRANSIT_ENCRYPTION_MODE_UNSPECIFIED'
    SERVER_AUTHENTICATION = 'SERVER_AUTHENTICATION'
    DISABLED = 'DISABLED'


class InstanceAuthString(BaseModel):
    authString: Optional[str] = Field(
        None, description='AUTH string set on the instance.'
    )


class Location(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The friendly name for this location, typically a nearby city name. For example, "Tokyo".',
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Cross-service attributes for the location. For example {"cloud.googleapis.com/region": "us-east1"}',
    )
    locationId: Optional[str] = Field(
        None, description='Resource ID for the region. For example: "us-east1".'
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='Output only. The set of available zones in the location. The map is keyed by the lowercase ID of each zone, as defined by Compute Engine. These keys can be specified in `location_id` or `alternative_location_id` fields when creating a Redis instance.',
    )
    name: Optional[str] = Field(
        None,
        description='Full resource name for the region. For example: "projects/example-project/locations/us-east1".',
    )


class MaintenanceSchedule(BaseModel):
    canReschedule: Optional[bool] = Field(
        None,
        description='If the scheduled maintenance can be rescheduled, default is true.',
    )
    endTime: Optional[str] = Field(
        None,
        description='Output only. The end time of any upcoming scheduled maintenance for this instance.',
    )
    scheduleDeadlineTime: Optional[str] = Field(
        None,
        description='Output only. The deadline that the maintenance schedule start time can not go beyond, including reschedule.',
    )
    startTime: Optional[str] = Field(
        None,
        description='Output only. The start time of any upcoming scheduled maintenance for this instance.',
    )


class NodeInfo(BaseModel):
    id: Optional[str] = Field(
        None,
        description="Output only. Node identifying string. e.g. 'node-0', 'node-1'",
    )
    zone: Optional[str] = Field(None, description='Output only. Location of the node.')


class OutputConfig(BaseModel):
    gcsDestination: Optional[GcsDestination] = Field(
        None, description='Google Cloud Storage destination for output content.'
    )


class PersistenceMode(Enum):
    PERSISTENCE_MODE_UNSPECIFIED = 'PERSISTENCE_MODE_UNSPECIFIED'
    DISABLED = 'DISABLED'
    RDB = 'RDB'


class RdbSnapshotPeriod(Enum):
    SNAPSHOT_PERIOD_UNSPECIFIED = 'SNAPSHOT_PERIOD_UNSPECIFIED'
    ONE_HOUR = 'ONE_HOUR'
    SIX_HOURS = 'SIX_HOURS'
    TWELVE_HOURS = 'TWELVE_HOURS'
    TWENTY_FOUR_HOURS = 'TWENTY_FOUR_HOURS'


class PersistenceConfig(BaseModel):
    persistenceMode: Optional[PersistenceMode] = Field(
        None,
        description='Optional. Controls whether Persistence features are enabled. If not provided, the existing value will be used.',
    )
    rdbNextSnapshotTime: Optional[str] = Field(
        None,
        description='Output only. The next time that a snapshot attempt is scheduled to occur.',
    )
    rdbSnapshotPeriod: Optional[RdbSnapshotPeriod] = Field(
        None,
        description='Optional. Period between RDB snapshots. Snapshots will be attempted every period starting from the provided snapshot start time. For example, a start time of 01/01/2033 06:45 and SIX_HOURS snapshot period will do nothing until 01/01/2033, and then trigger snapshots every day at 06:45, 12:45, 18:45, and 00:45 the next day, and so on. If not provided, TWENTY_FOUR_HOURS will be used as default.',
    )
    rdbSnapshotStartTime: Optional[str] = Field(
        None,
        description='Optional. Date and time that the first snapshot was/will be attempted, and to which future snapshots will be aligned. If not provided, the current time will be used.',
    )


class ExclusiveAction(Enum):
    UNKNOWN_REPAIR_ACTION = 'UNKNOWN_REPAIR_ACTION'
    DELETE = 'DELETE'
    RETRY = 'RETRY'


class ReconciliationOperationMetadata(BaseModel):
    deleteResource: Optional[bool] = Field(
        None, description='DEPRECATED. Use exclusive_action instead.'
    )
    exclusiveAction: Optional[ExclusiveAction] = Field(
        None, description='Excluisive action returned by the CLH.'
    )


class RescheduleType(Enum):
    RESCHEDULE_TYPE_UNSPECIFIED = 'RESCHEDULE_TYPE_UNSPECIFIED'
    IMMEDIATE = 'IMMEDIATE'
    NEXT_AVAILABLE_WINDOW = 'NEXT_AVAILABLE_WINDOW'
    SPECIFIC_TIME = 'SPECIFIC_TIME'


class RescheduleMaintenanceRequest(BaseModel):
    rescheduleType: Optional[RescheduleType] = Field(
        None,
        description='Required. If reschedule type is SPECIFIC_TIME, must set up schedule_time as well.',
    )
    scheduleTime: Optional[str] = Field(
        None,
        description='Optional. Timestamp when the maintenance shall be rescheduled to if reschedule_type=SPECIFIC_TIME, in RFC 3339 format, for example `2012-11-15T16:19:00.094Z`.',
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class TimeOfDay(BaseModel):
    hours: Optional[int] = Field(
        None,
        description='Hours of day in 24 hour format. Should be from 0 to 23. An API may choose to allow the value "24:00:00" for scenarios like business closing time.',
    )
    minutes: Optional[int] = Field(
        None, description='Minutes of hour of day. Must be from 0 to 59.'
    )
    nanos: Optional[int] = Field(
        None,
        description='Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.',
    )
    seconds: Optional[int] = Field(
        None,
        description='Seconds of minutes of the time. Must normally be from 0 to 59. An API may allow the value 60 if it allows leap-seconds.',
    )


class TlsCertificate(BaseModel):
    cert: Optional[str] = Field(None, description='PEM representation.')
    createTime: Optional[str] = Field(
        None,
        description='Output only. The time when the certificate was created in [RFC 3339](https://tools.ietf.org/html/rfc3339) format, for example `2020-05-18T00:00:00.094Z`.',
    )
    expireTime: Optional[str] = Field(
        None,
        description='Output only. The time when the certificate expires in [RFC 3339](https://tools.ietf.org/html/rfc3339) format, for example `2020-05-18T00:00:00.094Z`.',
    )
    serialNumber: Optional[str] = Field(
        None, description='Serial number, as extracted from the certificate.'
    )
    sha1Fingerprint: Optional[str] = Field(
        None, description='Sha1 Fingerprint of the certificate.'
    )


class UpgradeInstanceRequest(BaseModel):
    redisVersion: Optional[str] = Field(
        None,
        description='Required. Specifies the target version of Redis software to upgrade to.',
    )


class Day(Enum):
    DAY_OF_WEEK_UNSPECIFIED = 'DAY_OF_WEEK_UNSPECIFIED'
    MONDAY = 'MONDAY'
    TUESDAY = 'TUESDAY'
    WEDNESDAY = 'WEDNESDAY'
    THURSDAY = 'THURSDAY'
    FRIDAY = 'FRIDAY'
    SATURDAY = 'SATURDAY'
    SUNDAY = 'SUNDAY'


class WeeklyMaintenanceWindow(BaseModel):
    day: Optional[Day] = Field(
        None, description='Required. The day of week that maintenance updates occur.'
    )
    duration: Optional[str] = Field(
        None,
        description='Output only. Duration of the maintenance window. The current window is fixed at 1 hour.',
    )
    startTime: Optional[TimeOfDay] = Field(
        None, description='Required. Start time of the window in UTC time.'
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class ExportInstanceRequest(BaseModel):
    outputConfig: Optional[OutputConfig] = Field(
        None, description='Required. Specify data to be exported.'
    )


class GoogleCloudRedisV1LocationMetadata(BaseModel):
    availableZones: Optional[Dict[str, GoogleCloudRedisV1ZoneMetadata]] = Field(
        None,
        description='Output only. The set of available zones in the location. The map is keyed by the lowercase ID of each zone, as defined by GCE. These keys can be specified in `location_id` or `alternative_location_id` fields when creating a Redis instance.',
    )


class ImportInstanceRequest(BaseModel):
    inputConfig: Optional[InputConfig] = Field(
        None, description='Required. Specify data to be imported.'
    )


class ListLocationsResponse(BaseModel):
    locations: Optional[List[Location]] = Field(
        None,
        description='A list of locations that matches the specified filter in the request.',
    )
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )


class MaintenancePolicy(BaseModel):
    createTime: Optional[str] = Field(
        None, description='Output only. The time when the policy was created.'
    )
    description: Optional[str] = Field(
        None,
        description='Optional. Description of what this policy is for. Create/Update methods return INVALID_ARGUMENT if the length is greater than 512.',
    )
    updateTime: Optional[str] = Field(
        None, description='Output only. The time when the policy was last updated.'
    )
    weeklyMaintenanceWindow: Optional[List[WeeklyMaintenanceWindow]] = Field(
        None,
        description='Optional. Maintenance window that is applied to resources covered by this policy. Minimum 1. For the current version, the maximum number of weekly_window is expected to be one.',
    )


class Operation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[Status] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='{ `createTime`: The time the operation was created. `endTime`: The time the operation finished running. `target`: Server-defined resource path for the target of the operation. `verb`: Name of the verb executed by the operation. `statusDetail`: Human-readable status of the operation, if any. `cancelRequested`: Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. `apiVersion`: API version used to start the operation. }',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.',
    )
    response: Optional[Dict[str, Any]] = Field(
        None,
        description='The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.',
    )


class Instance(BaseModel):
    alternativeLocationId: Optional[str] = Field(
        None,
        description='Optional. If specified, at least one node will be provisioned in this zone in addition to the zone specified in location_id. Only applicable to standard tier. If provided, it must be a different zone from the one provided in [location_id]. Additional nodes beyond the first 2 will be placed in zones selected by the service.',
    )
    authEnabled: Optional[bool] = Field(
        None,
        description='Optional. Indicates whether OSS Redis AUTH is enabled for the instance. If set to "true" AUTH is enabled on the instance. Default value is "false" meaning AUTH is disabled.',
    )
    authorizedNetwork: Optional[str] = Field(
        None,
        description='Optional. The full name of the Google Compute Engine [network](https://cloud.google.com/vpc/docs/vpc) to which the instance is connected. If left unspecified, the `default` network will be used.',
    )
    availableMaintenanceVersions: Optional[List[str]] = Field(
        None,
        description='Optional. The available maintenance versions that an instance could update to.',
    )
    connectMode: Optional[ConnectMode] = Field(
        None,
        description='Optional. The network connect mode of the Redis instance. If not provided, the connect mode defaults to DIRECT_PEERING.',
    )
    createTime: Optional[str] = Field(
        None, description='Output only. The time the instance was created.'
    )
    currentLocationId: Optional[str] = Field(
        None,
        description='Output only. The current zone where the Redis primary node is located. In basic tier, this will always be the same as [location_id]. In standard tier, this can be the zone of any node in the instance.',
    )
    customerManagedKey: Optional[str] = Field(
        None,
        description='Optional. The KMS key reference that the customer provides when trying to create the instance.',
    )
    displayName: Optional[str] = Field(
        None,
        description='An arbitrary and optional user-provided name for the instance.',
    )
    host: Optional[str] = Field(
        None,
        description='Output only. Hostname or IP address of the exposed Redis endpoint used by clients to connect to the service.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='Resource labels to represent user provided metadata'
    )
    locationId: Optional[str] = Field(
        None,
        description='Optional. The zone where the instance will be provisioned. If not provided, the service will choose a zone from the specified region for the instance. For standard tier, additional nodes will be added across multiple zones for protection against zonal failures. If specified, at least one node will be provisioned in this zone.',
    )
    maintenancePolicy: Optional[MaintenancePolicy] = Field(
        None,
        description='Optional. The maintenance policy for the instance. If not provided, maintenance events can be performed at any time.',
    )
    maintenanceSchedule: Optional[MaintenanceSchedule] = Field(
        None,
        description='Output only. Date and time of upcoming maintenance events which have been scheduled.',
    )
    maintenanceVersion: Optional[str] = Field(
        None,
        description='Optional. The self service update maintenance version. The version is date based such as "20210712_00_00".',
    )
    memorySizeGb: Optional[int] = Field(
        None, description='Required. Redis memory size in GiB.'
    )
    name: Optional[str] = Field(
        None,
        description='Required. Unique name of the resource in this scope including project and location using the form: `projects/{project_id}/locations/{location_id}/instances/{instance_id}` Note: Redis instances are managed and addressed at regional level so location_id here refers to a GCP region; however, users may choose which specific zone (or collection of zones for cross-zone instances) an instance should be provisioned in. Refer to location_id and alternative_location_id fields for more details.',
    )
    nodes: Optional[List[NodeInfo]] = Field(
        None, description='Output only. Info per node.'
    )
    persistenceConfig: Optional[PersistenceConfig] = Field(
        None, description='Optional. Persistence configuration parameters'
    )
    persistenceIamIdentity: Optional[str] = Field(
        None,
        description='Output only. Cloud IAM identity used by import / export operations to transfer data to/from Cloud Storage. Format is "serviceAccount:". The value may change over time for a given instance so should be checked before each import/export operation.',
    )
    port: Optional[int] = Field(
        None, description='Output only. The port number of the exposed Redis endpoint.'
    )
    readEndpoint: Optional[str] = Field(
        None,
        description="Output only. Hostname or IP address of the exposed readonly Redis endpoint. Standard tier only. Targets all healthy replica nodes in instance. Replication is asynchronous and replica nodes will exhibit some lag behind the primary. Write requests must target 'host'.",
    )
    readEndpointPort: Optional[int] = Field(
        None,
        description="Output only. The port number of the exposed readonly redis endpoint. Standard tier only. Write requests should target 'port'.",
    )
    readReplicasMode: Optional[ReadReplicasMode] = Field(
        None,
        description='Optional. Read replicas mode for the instance. Defaults to READ_REPLICAS_DISABLED.',
    )
    redisConfigs: Optional[Dict[str, str]] = Field(
        None,
        description='Optional. Redis configuration parameters, according to http://redis.io/topics/config. Currently, the only supported parameters are: Redis version 3.2 and newer: * maxmemory-policy * notify-keyspace-events Redis version 4.0 and newer: * activedefrag * lfu-decay-time * lfu-log-factor * maxmemory-gb Redis version 5.0 and newer: * stream-node-max-bytes * stream-node-max-entries',
    )
    redisVersion: Optional[str] = Field(
        None,
        description='Optional. The version of Redis software. If not provided, latest supported version will be used. Currently, the supported values are: * `REDIS_3_2` for Redis 3.2 compatibility * `REDIS_4_0` for Redis 4.0 compatibility (default) * `REDIS_5_0` for Redis 5.0 compatibility * `REDIS_6_X` for Redis 6.x compatibility',
    )
    replicaCount: Optional[int] = Field(
        None,
        description='Optional. The number of replica nodes. The valid range for the Standard Tier with read replicas enabled is [1-5] and defaults to 2. If read replicas are not enabled for a Standard Tier instance, the only valid value is 1 and the default is 1. The valid value for basic tier is 0 and the default is also 0.',
    )
    reservedIpRange: Optional[str] = Field(
        None,
        description='Optional. For DIRECT_PEERING mode, the CIDR range of internal addresses that are reserved for this instance. Range must be unique and non-overlapping with existing subnets in an authorized network. For PRIVATE_SERVICE_ACCESS mode, the name of one allocated IP address ranges associated with this private service access connection. If not provided, the service will choose an unused /29 block, for example, 10.0.0.0/29 or 192.168.0.0/29. For READ_REPLICAS_ENABLED the default block size is /28.',
    )
    secondaryIpRange: Optional[str] = Field(
        None,
        description='Optional. Additional IP range for node placement. Required when enabling read replicas on an existing instance. For DIRECT_PEERING mode value must be a CIDR range of size /28, or "auto". For PRIVATE_SERVICE_ACCESS mode value must be the name of an allocated address range associated with the private service access connection, or "auto".',
    )
    serverCaCerts: Optional[List[TlsCertificate]] = Field(
        None,
        description='Output only. List of server CA certificates for the instance.',
    )
    state: Optional[State] = Field(
        None, description='Output only. The current state of this instance.'
    )
    statusMessage: Optional[str] = Field(
        None,
        description='Output only. Additional information about the current status of this instance, if available.',
    )
    suspensionReasons: Optional[List[SuspensionReason]] = Field(
        None, description='Optional. reasons that causes instance in "SUSPENDED" state.'
    )
    tier: Optional[Tier] = Field(
        None, description='Required. The service tier of the instance.'
    )
    transitEncryptionMode: Optional[TransitEncryptionMode] = Field(
        None,
        description='Optional. The TLS mode of the Redis instance. If not provided, TLS is disabled for the instance.',
    )


class ListInstancesResponse(BaseModel):
    instances: Optional[List[Instance]] = Field(
        None,
        description='A list of Redis instances in the project in the specified location, or across all locations. If the `location_id` in the parent field of the request is "-", all regions available to the project are queried, and the results aggregated. If in such an aggregated query a location is unavailable, a placeholder Redis entry is included in the response with the `name` field set to a value of the form `projects/{project_id}/locations/{location_id}/instances/`- and the `status` field set to ERROR and `status_message` field set to "location not available for ListInstances".',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='Token to retrieve the next page of results, or empty if there are no more results in the list.',
    )
    unreachable: Optional[List[str]] = Field(
        None, description='Locations that could not be reached.'
    )


class ListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[Operation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )
